COW-dev/eat-da-be

- .github/auto_assign.yml
> [Etc] auto assign 설정 변경

- .github/workflows/codecov.yml
- codecov 연동 action workflow 정의
> [ETA] codecov action 추가

- .editorconfig
- .github/workflows/ktlint-check.yml
- build.gradle.kts
- settings.gradle.kts
- src/test/kotlin/com/mjucow/eatda/EatdaApplicationTests.kt
- ktlint gradle 의존성 추가 및 github action(ktlint-check) 추가
> [Etc] Ktlint gradle 설정 및 github action 추가

- .github/workflows/test.yml
- gradle.properties
- gradle test 실행 github action 추가
> [etc] setup ci test github action

- .editorconfig
> [etc] kt, kts 파일 마지막 줄 개행하는 걸로 변경

- src/main/kotlin/com/mjucow/eatda/EatdaApplication.kt
- src/main/kotlin/com/mjucow/eatda/domain/common/BaseEntity.kt
- 기본 entity 클래스 정의 및 auditing 추가
> [feature] add auditing and create base entity

- .editorconfig
- src/main/kotlin/com/mjucow/eatda/presentation/common/ApiResponse.kt
- src/main/kotlin/com/mjucow/eatda/presentation/common/DomainControllerAdvice.kt
- src/main/kotlin/com/mjucow/eatda/presentation/common/GlobalControllerAdvice.kt
- src/main/kotlin/com/mjucow/eatda/presentation/common/GlobalExceptionHandler.kt
- ApiResponse를 포함한 공통 예외처리 컨트롤러 구현
> [feature] 공통 예외처리 컨트롤러 구현

- src/main/kotlin/com/mjucow/eatda/domain/store/category/Category.kt
- src/main/resources/application.yml
- store에 적용되는 category entity 정의
- local 환경에서 사용되는 ddl-auto 옵션 삭제
> [feature] category entity 정의

- compose.yaml
- src/main/resources/application.yml
- src/main/resources/db/changelog/changelog-master.yml
- src/main/resources/logback/logback-local.xml
> [style] xml, yaml 들여쓰기 수정

- build.gradle.kts
- gradle.properties
- src/test/resources/application.yml
- [mockk](https://mockk.io/)([spring-mockk](https://github.com/Ninja-Squad/springmockk))를 추가하고 srping-boot-test의 mockito-core를 제외
> [etc] springmockk 의존성 추가 및 mockito-core 제외

- .github/workflows/codecov.yml
- codecov에서 불필요한 동작을 제거(현재 codecov가 활성화가 안되어 있어 예시 action처럼 수정)
> [etc] codecov 불필요한 동작 제거 

- codecov.yml
> [etc] codecov 설정 파일 추가

- build.gradle.kts
- src/main/kotlin/com/mjucow/eatda/common/vo/DayOfWeek.kt
- src/main/kotlin/com/mjucow/eatda/domain/store/entity/Store.kt
- src/main/kotlin/com/mjucow/eatda/domain/store/entity/StoreHours.kt
- src/main/resources/db/changelog/230929-store_hours.sql
- src/test/kotlin/com/mjucow/eatda/domain/store/entity/StoreHoursTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/entity/StoreTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/EntityMother.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/ObjectMother.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/StoreHoursMother.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/StoreMother.kt
- store hours domain 정의 및 테스트 작성
- DayOfWeek 클래스의 하루 전후 비교하는 메서드가 필요한지? 없으면 또 가독성이 너무 떨어질 것 같기도 하고...?! 이름도 뭔가 직관적인지 헷갈리는 지 모르겠음
> [feature] storehours domain 정의 및 테스트 작성

- src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
- src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/StoreDetailDto.kt
- src/main/kotlin/com/mjucow/eatda/persistence/store/StoreRepository.kt
- src/main/kotlin/com/mjucow/eatda/presentation/store/StoreController.kt
- src/main/resources/static/swagger-ui/openapi3.yaml
- src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
- src/test/kotlin/com/mjucow/eatda/presentation/AbstractMockMvcTest.kt
- src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
- src/test/kotlin/com/mjucow/eatda/presentation/store/category/CategoryMvcTest.kt
- store api 구현 및 테스트 작성
- category rest docs tag 및 identifier 정리
> [feature] store api 구현 및 테스트 작성

- src/main/kotlin/com/mjucow/eatda/domain/store/entity/Menu.kt
- src/main/resources/db/changelog/231014-menu.sql
- src/test/kotlin/com/mjucow/eatda/domain/store/entity/MenuTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/MenuMother.kt
- 메뉴 도메인 정의 및 sql 작성
- 메뉴 관련 테스트 작성 및 오브젝트마더 구현
> [feature] menu 도메인 정의 및 테스트 작성

- src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/NoticeCommandService.kt
- src/main/kotlin/com/mjucow/eatda/domain/notice/service/query/NoticeQueryService.kt
- src/main/kotlin/com/mjucow/eatda/domain/store/service/command/CategoryCommandService.kt
- src/main/kotlin/com/mjucow/eatda/domain/store/service/command/StoreCommandService.kt
- src/main/kotlin/com/mjucow/eatda/domain/store/service/query/CategoryQueryService.kt
- src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/service/query/CategoryQueryServiceDataTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
- 불필요한 `findByOrNull + throw Exception`을 `getReferenceById`으로 변경
- 필요한 곳에서만 `findByIdOrNull`을 사용하고 확실히 가져와야 할 때는 `getReferenceById`을 쓰는 것으로!
close #32
> [refactor] findByIdOrNull -> getReferenceById

- src/main/kotlin/com/mjucow/eatda/domain/store/service/command/MenuCommandService.kt
- src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/MenuCreateCommand.kt
- src/main/kotlin/com/mjucow/eatda/domain/store/service/command/dto/MenuUpdateCommand.kt
- src/main/kotlin/com/mjucow/eatda/domain/store/service/query/MenuDto.kt
- src/main/kotlin/com/mjucow/eatda/domain/store/service/query/MenuQueryService.kt
- src/main/kotlin/com/mjucow/eatda/domain/store/service/query/dto/MenuList.kt
- src/main/kotlin/com/mjucow/eatda/persistence/store/MenuRepository.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/entity/objectmother/MenuMother.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/service/command/MenuCommandServiceTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/service/query/MenuQueryServiceTest.kt
- Menu Application 구현 및 테스트 작성
> [feature] menu application 구현 및 테스트 작성

- .run/EatdaApplication.run.xml
- src/main/resources/static/swagger-ui/openapi3.yaml
- src/test/kotlin/com/mjucow/eatda/domain/store/service/query/CategoryQueryServiceDataTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
- src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
- src/test/kotlin/com/mjucow/eatda/presentation/store/category/CategoryMvcTest.kt
- src/test/kotlin/com/mjucow/eatda/presentation/store/menu/MenuControllerMvcTest.kt
- open api 재생성 및 정리
- tag 소문자로 정리
> [etc] update open api

- src/test/kotlin/com/mjucow/eatda/domain/notice/entity/NoticeTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/notice/service/command/NoticeCommandServiceTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/notice/service/query/NoticeQueryServiceTest.kt
> [etc] 테스트 문구 수정

- .github/workflows/release-drafter-config.yml
- .github/workflows/release-drafter.yml
- 릴리즈 노트 자동 작성을 위한 드래프트 생성 깃허브 액션 추가
> [etc] add release drafter github action

- compose.yaml
- src/test/kotlin/com/mjucow/eatda/AbstractApplicationTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/AbstractDataTest.kt
- rds support verison 이슈로 15.4로 버전을 내립니다.
> [fix] downgrade postgres version

- .github/release-drafter.yml
- release drater에서 etc label maintanance로 처리하도록 변경
> [etc] etc tag maintanance로 처리

- .github/workflows/deploy.yml
- Dockerfile
- build.gradle.kts
- compose.yaml
- gradle.properties
- src/main/resources/application.yml
- src/main/resources/logback/logback-prod.xml
- src/test/kotlin/com/mjucow/eatda/AbstractApplicationTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/AbstractDataTest.kt
- 배포용 github action 추가
- config file 및 logback file 작성
> [etc] 배포 준비

- .github/release-drafter.yml
- .github/workflows/deploy.yml
- Dockerfile
- build.gradle.kts
- compose.yaml
- gradle.properties
- src/main/resources/application.yml
- src/main/resources/logback/logback-prod.xml
> v.0.1.0-Release

- .github/workflows/deploy.yml
> [etc] fix deploy yml

- .github/workflows/deploy.yml
> v.0.1.1-Release

- .github/workflows/deploy.yml
> [etc] change aws credential

- .github/workflows/deploy.yml
> v0.1.2-Release

- .github/workflows/deploy.yml
- gradle.properties
> [etc] update ssh key

- .github/workflows/deploy.yml
- gradle.properties
> v0.1.3-Release

- .github/workflows/deploy.yml
- .gitignore
- build.gradle.kts
- compose.yaml
- src/main/kotlin/com/mjucow/eatda/common/config/RedisConfiguration.kt
- src/main/kotlin/com/mjucow/eatda/common/properties/PropertiesConfiguration.kt
- src/main/kotlin/com/mjucow/eatda/common/properties/RedisProperties.kt
- src/main/resources/application.yml
- src/test/kotlin/com/mjucow/eatda/domain/AbstractCacheTest.kt
- src/test/resources/application.yml
> [etc] redis set up

- .github/workflows/deploy.yml
> [etc] fix deploy command

- build.gradle.kts
- src/main/kotlin/com/mjucow/eatda/common/config/RedisConfiguration.kt
- src/main/kotlin/com/mjucow/eatda/domain/poplarstore/entity/PopularStore.kt
- src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCacheService.kt
- src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCommandService.kt
- src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreQueryService.kt
- src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/dto/PopularStoreDto.kt
- src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/dto/PopularStoreDtos.kt
- src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
- src/main/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreController.kt
- src/test/kotlin/com/mjucow/eatda/domain/AbstractCacheTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCacheServiceTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCommandServiceTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreQueryServiceTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
- src/test/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreControllerTest.kt
- src/test/resources/application.yml
- popular store 기능 구현
- popular store 테스트 작성(진행중)
- [기획 노션](https://www.notion.so/eat-da/v1-0-be407b29b21e41fa89649186b1a051bd?pvs=4)
> [feature] popular store

- .github/workflows/deploy.yml
- src/main/resources/static/swagger-ui/openapi3.yaml
- src/test/kotlin/com/mjucow/eatda/presentation/banner/BannerMvcTest.kt
- src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
> [fix] swagger tag

- .github/workflows/deploy.yml
- .gitignore
- build.gradle.kts
- compose.yaml
- src/main/kotlin/com/mjucow/eatda/common/config/RedisConfiguration.kt
- src/main/kotlin/com/mjucow/eatda/common/properties/PropertiesConfiguration.kt
- src/main/kotlin/com/mjucow/eatda/common/properties/RedisProperties.kt
- src/main/kotlin/com/mjucow/eatda/domain/poplarstore/entity/PopularStore.kt
- src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCacheService.kt
- src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCommandService.kt
- src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreQueryService.kt
- src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/dto/PopularStoreDto.kt
- src/main/kotlin/com/mjucow/eatda/domain/poplarstore/service/dto/PopularStoreDtos.kt
- src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
- src/main/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreController.kt
- src/main/resources/application.yml
- src/main/resources/static/swagger-ui/openapi3.yaml
- src/test/kotlin/com/mjucow/eatda/domain/AbstractCacheTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCacheServiceTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreCommandServiceTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/poplarstore/service/PopularStoreQueryServiceTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
- src/test/kotlin/com/mjucow/eatda/presentation/banner/BannerMvcTest.kt
- src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
- src/test/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreControllerTest.kt
- src/test/resources/application.yml
> v0.1.4-Release

- .github/workflows/deploy.yml
> [etc] build with gradle command

- .github/workflows/deploy.yml
> [etc] build with gradle command (#58)

- .github/workflows/deploy.yml
- src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
- src/main/resources/application.yml
> [fix] store cache call

- src/main/resources/application.yml
> [etc] add port in config

- src/test/kotlin/com/mjucow/eatda/AbstractApplicationTest.kt
- src/test/kotlin/com/mjucow/eatda/AbstractSpringContextTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/AbstractCacheTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/AbstractDataTest.kt
- src/test/resources/application.yml
> [refactor] remove postgreqsql test container

- build.gradle.kts
- gradle.properties
- src/main/kotlin/com/mjucow/eatda/common/config/WebConfig.kt
- src/test/kotlin/com/mjucow/eatda/AbstractApplicationTest.kt
- src/test/kotlin/com/mjucow/eatda/AbstractSpringContextTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/AbstractCacheTest.kt
- src/test/kotlin/com/mjucow/eatda/domain/AbstractDataTest.kt
- src/test/resources/application.yml
> v0.1.5-Release

- .github/CODEOWNERS
> [etc] CODEOWNERS 수정

- gradle.properties
> [etc]Spring boot version 3.1.2 -> 3.1.6

- gradle.properties
- src/main/kotlin/com/mjucow/eatda/common/config/SwaggerConfig.kt
> [etc] version 수정

- src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
- src/main/kotlin/com/mjucow/eatda/presentation/store/StoreApiPresentation.kt
- src/main/kotlin/com/mjucow/eatda/presentation/store/StoreController.kt
- src/test/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryServiceDataTest.kt
- src/test/kotlin/com/mjucow/eatda/presentation/store/StoreControllerMvcTest.kt
- 커서 기반 가게 조회 api - storeId → cursor 수정
> [etc] storeId → cursor 수정

- .run/EatdaApplication.run.xml
- build.gradle.kts
- src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
- src/main/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreController.kt
- src/test/kotlin/com/mjucow/eatda/presentation/store/popularstore/PopularStoreControllerTest.kt
> [fix] redis 분리 및 api 추가

- src/main/kotlin/com/mjucow/eatda/health/HealthCheckController.kt
> [etc] health check controller 추가

- build.gradle.kts
- src/main/kotlin/com/mjucow/eatda/health/HealthCheckController.kt
> [fix] test ignore and ktlint

- .github/workflows/deploy.yml
> [fix] 배포 스크립트 s3 인자 추가
